const cardImages = {
 "Luke Skywalker": "./luke.png",
 "C-3PO": "./c3p0.png",
 "R2-D2": "./r2d2.png",
 "Darth Vader": "./darthvader.png",
 "Leia Organa": "./leia.png",
 "Owen Lars": "./owen.png",
 "Beru Whitesun lars": "./beru.png",
 "R5-D4": "./r5d4.png",
 "Biggs Darklighter": "./bigg.png",
 "Obi-Wan Kenobi": "./obiwan.png",
 "Alderaan": "./alderaan.png",
 "AT-AT": "./atat.png",
 "AT-ST": "./atst.png",
 "Bespin": "./bespin.png",
 "Coruscant": "./coruscant.png",
 "Dagobah": "./dagobah.png",
 "Endor":"./endor.png",
 "Geonosis": "./geonosis.png",
 "Hoth": "./hoth.png",
 'Kamino': "./kamino.png",
 "Naboo": "naboo.png",
 "Sail barge": "./sailbarge.png",
 "Sand Crawler": "./sandcrawler.png",
 "Snowspeeder": "./snowspeeder.png",
 "Storm IV Twin-Pod cloud car": './cloudcar.png',
 "T-16 skyhopper": "./t16skyhopper.png",
 "TIE bomber": "./tiebomber.png",
 "TIE/LN starfighter": "./tiefighter.png",
 "X-34 landspeeder": "./x34landspeeder.png",
 "Yavin IV": "./yavin4.png"
}

export default cardImages;